[package]
name = "timeboost-proto"
description = "Timeboost protobuf types"
edition = "2024"

[dependencies]
tonic = { workspace = true }
tonic-prost = { workspace = true }
prost = { workspace = true }
